# Generated by Django 5.1.3 on 2024-12-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_staffleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleave',
            name='subject',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
