# Generated by Django 5.1.3 on 2024-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_staffleave_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleave',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
