# Generated by Django 5.1.3 on 2024-12-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_studentfeedback_is_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffeedback',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
